name: Release - manual

on:
  workflow_dispatch:
    inputs:
      version_input:
        description: 'Enter the version'
        required: true
        default: 11.81.0-release.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Try building
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p bins
          uv run main.py --m 1 --v ${{ github.event.inputs.version_input }}
